### ISSUE TITLE
Question on the JobStorage - How to implement another one?

### ISSUE THREAD

**Issue by sebalix** [OCA/connector#126]
Hi,

One of the bottleneck of the connector is the way it stores the jobs (in the database). I was thinking about another storage like Redis or RabbitMQ to speed up the job creation/consumption, and I just seen that there is already some abstraction about this with the `JobStorage` class and the implementation `OpenERPJobStorage`.
But the last one seems used as a direct dependency by the Web controller, the `queue.job` model, the `Worker` class, and the `Job.delay` method.

Is there any thoughts about this? If we want to provide different storage backends for the jobs/tasks in the future, is this have to be implemented in another module (e.g. `connector_redis`, with some monkey-patches/overloads of `connector` elements) or integrated directly in the `connector` (and choose the storage backend through some system parameters)?

In fact, I need some performance on a project (just a test), and started to think about the integration of [Celery](http://www.celeryproject.org/) for the tasks, but it is a bit redundant with the connector framework, that's why I am asking some info/feedback on this topic!

**Comment by guewen** [comment]
Back then, I abstracted the `OpenERPJobStorage` with this use case in mind. At the time, I thought that it would be better with another module such as `connector_redis` than directly integrated. You are right, a way to change the strategy of storage does not exist yet. Since then, I have the feeling that the jobs queue became more tied to Postgresql and it could maybe be difficult to detach from it. Note that the `Worker` class is meant to disappear in favor of the jobrunner.

Something you will need to take care of will be the creation of the jobs within the same transaction than Postgresql (or jobs may become invalid if the transaction is rollbacked). Before starting `connector`, I did some attempts including `celery` and wrote this [monkey-patch](https://github.com/guewen/redux/blob/master/magentoerpconnect_redux/sql_db.py) (and it should ideally use 2-phase commits).

In any case, I'm very interested in your progression on this matter and I would gladly accept patches that would ease this integration.

**Comment by sebalix** [comment]
Cool, thanks for these informations and the link, very useful indeed. As soon as I progress on this I will make some PRs if there is an opportunity to extract the PostgreSQL logic from some elements.

**Comment by sbidoul** [comment]
@sebalix out of curiosity, what drawbacks do you see with storing jobs in the database?

**Comment by sebalix** [comment]
@sbidoul it is a bit slow when we create several thousands of jobs, and in the same time the workers start to consume them (updating the state/attempts), it generates a lot of I/O which could be avoid - I think - if the creation/consumption of tasks is done directly in memory or at least to a dedicated system like Redis/RabbitMQ (running on another host if we want to). Maybe I'm wrong, but I want to experiment on this to see if the speed can be improved.

For instance, during a data import, we created about 300k jobs. It takes already a lot of time just to create these 300k rows in the database through the ORM (either all of them in oneshot, or by chunk of 1000 to let the workers starting to process them). If these 300k jobs can be created in a subsystem like Redis, we could gain a lot of time.

**Comment by guewen** [comment]
An option could be to keep the queue_job model for creating jobs, so they still benefit from the transactional properties of the database, then they are offloaded by batches to an external queue such as rabbitMQ. In that case, the job runner would not be started and we would need another kind of jobrunner / adaptation of the jobrunner which gets jobs from the queue rather than postgres.
