### ISSUE TITLE
component: Improve to have sudo() equivalent (or with_user())

### ISSUE THREAD

**Issue by rousseldenis** [OCA/connector#365]
Sometimes, it should be interesting to have such method in components behaviour.

@guewen Do you have an advice or do you have ever thought about including this ?

**Comment by guewen** [comment]
IIRC this is why @jcoux opened https://github.com/OCA/connector/pull/359
In order to be able to do this in a custom project:

```python
        old_collection = self.collection
        self.work.collection = self.collection.sudo(user.id)
        super()._import(binding_id)
        self.work.collection = old_collection
```

The method to change the user could be directly added in `WorkContext`.
What I'm unsure is:
1. a context manager that revert the user at exit? 
2. change the user directly in the WorkContext instance without reverting to the previous user? 
3. create a copy of the WorkContext with `work_on()` and the new collection recordset?

I prefer 3 because it leaves the inital WorkContext untouched and reflects how the change of user on a recordset works, but I didn't think thorougly of the use cases.

**Comment by simahawk** [comment]
gut feeling: go for pt 3. We could have smth like:
```py
with self.work.sudo_work_on(user=...) as sudo_work:
```

**Comment by guewen** [comment]
my proposition 3. was not using a context manager, the current `WorkContext.work_on` method isn't either (on the backend model it is, in order to have the ability to handle the closure of an instance we pass to the work context, such as an api/sftp client):

https://github.com/OCA/connector/blob/84e41a6279d7896e33e8d0248a0363a26aadd9ce/component/core.py#L275-L288

I thought about adding this in the WorkContext class:

```python
def with_user(self, user):
    if not user:
        return self
    return self.work_on(collection=self.collection.with_user(user))
```

Usage:

```python
with my_backend.work_on(foo=1) as work:
    work_with_user = work.with_user(other_user)
    component_with_user = work_with_user.component(usage='bar')
    component_with_default_user = work.component(usage='bar')
```
