### ISSUE TITLE
worker is not supported dbfilter with %d or %h parameter.

### ISSUE THREAD

**Issue by ghost** [OCA/connector#58]
This connector worker is not supported with the dbfilter having either %d or %h.
i.e. dbfilter = '^%d.*' then it is not working with the following line of code.
dbfilter = config['dbfilter']
if dbfilter and db_names:
    db_names = [d for d in db_names if re.match(dbfilter, d)]

here dbfilter variable having '^%d.*' thats why re.match will not found any matches with this and it is returning [ ](blank list).

same this openerp-connector-worker script is not working with dbfilter.

**Comment by guewen** [comment]
The `--db-filter` option is an option filtering what databases are shown on the web interface.
I'm not sure that it should restrict the job workers. The `--database` option seems more appropriate for this to me.

**Comment by sbidoul** [comment]
I think the runner should honor `--db-filter`. For example, you may want a configuration with two odoo instances on the same machine, each serving a different set of databases controlled by `--db-filter`. The runner should listen to the exact same set of databases than the Odoo instance it's running in.

I did not know dbfilter could include %d. I thought I had copied the same db filtering algorithm as the Odoo server. To be verified.

**Comment by guewen** [comment]
@sbidoul here is my interpretation:
`--db-filter` only restricts HTTP to serve databases which are not in the filter. It does not prevent for instance the crons to run on those databases. The option that really makes Odoo (including crons) run on a selection of databases is `--database`. So in your case, with 2 odoo on the same machine but different set of databases, you should probably configure a different `--database` option otherwise your cron will be mixed up between all the databases. I think the job runner should have the same behavior than the cron.

**Comment by sbidoul** [comment]
@guewen It seems you are right indeed. I remember now where I got this part of code from: I copied it from the connector worker :wink: 

Still it's a bit strange to me. If you use `%h` and `%d` in the dbfilter, this means that you probably don't use `--database` and the Odoo instance sees databases served by other hosts. So the crons will run on all of them and compete to catch the jobs. That's probably a minor issues for crons which will lock the jobs anyway and prevent the same job to be run by two instance at the same time.

But for the runner, if it ignores dbfilter, it will listen (and create connections) to all visible databases.

So I would rather keep using dbfilter and use http.db_filter() in https://github.com/OCA/connector/blob/8.0/connector/jobrunner/runner.py#L221

**Comment by flotho** [comment]
Hi folks,

I think I have this kind of issue. I run successfully the connector-worker yet no worker is added in the db that has the connector installed.
I'm not sure to have understand if there is a workaround. 

Thanks in advance.

Edit : adding the db filter on the connector command works very well of course!

**Comment by lepri** [comment]
I have this issue using dbfilter. After remover the filter ^%d$ the connector works fine.

**Comment by guewen** [comment]
> So I would rather keep using dbfilter and use http.db_filter() in https://github.com/OCA/connector/blob/8.0/connector/jobrunner/runner.py#L221

Ok, I trust you on that, I'm not very familiar with `--db-filter` because usually we create postgres users so that we have 1 database available at a time.

**Comment by YannickB** [comment]
Same for me, I confirm that when you use a db_filter no workers appear on the connector interface, whether you use monoworker, multiworker with openerp-connector-worker or jobrunner.

In fact, you never see in the log anything related to the database, so for me the connector is just unable to see the databases, probably because of db_filter. Even if you specify the database directly with -d option

My configuration : 
db_filter = ^odoo_%h$
database name : odoo_customer_clouder_at
my url : customer.clouder.at

**Comment by guewen** [comment]
@YannickB the correct option is `dbfilter`, is it a typo in your comment?

**Comment by YannickB** [comment]
Yep it is a typo

**Comment by LeartS** [comment]
I have the same issue, spent a long time trying to find out why connector wasn't working!

**Comment by sbidoul** [comment]
Fixed in 
- https://github.com/OCA/connector/commit/2290696377641fdc6f621ae70377b9333ae7e27b (8.0)
- https://github.com/acsone/connector/commit/3c83de414638d955f4e302cb1f00a749b2bd5029 (9.0)
