### ISSUE TITLE
Object Domain

### ISSUE THREAD

**Issue by agb80** [OCA/connector#83]
I'm working on a new connector module to integrate OpenERP with Drupal Commerce, later will try to publish under OCA, but for now I wonder if there is a some tool that we could leverage for follow user case:

OpenERP will hold the master data for product categories and products but not all the products will be available on the Drupal store so we need a way to filter what products will be upload into the Drupal website.

At this moment I'm hardcoding the domain on the export functions but don't seems very elegant or extensible way, is there any other way available on connector?

**Comment by guewen** [comment]
The thing that means "this record X must be exported to the backend Y" is the binding record. Let's say you have a binding model `drupal.product.product` for the products, as soon as a new record is created on this model for a product and a backend, it means that an export of this product must be done on this backend. 

You can have a look at this simple export module : https://github.com/guewen/connector-magento/tree/8.0-magentoerpconnect_export_partner-migr/magentoerpconnect_export_partner

And especially https://github.com/guewen/connector-magento/blob/8.0-magentoerpconnect_export_partner-migr/magentoerpconnect_export_partner/consumer.py

Since we export bindings (or records with a binding) as soon as they are created or modified, we don't need to filter on products that we want to export.

If you prefer to have a regular export with a domain, you would just have to search all records on `drupal.product.product` with a filter on the backend you are exporting to.

**Comment by agb80** [comment]
Thanks a lot for your answer @guewen based on your answer I create a wizard that allow user create binding objects from selected objects on OpenERP tree view so the user is able to dynamically select what objects they need to be exported into the Drupal website.

If anybody is interested, we are working on Drupal connector here: https://github.com/OpenPymeMx/connector-drupal plan to propose to OCA when its ready.

**Comment by guewen** [comment]
Thanks for the notice about the drupal connector! Interesting indeed. Come back again to me when you think it is mature enough to be added on the list of connector on odoo-connector.com :-)

**Comment by guewen** [comment]
You got the idea right :-)
